sudo: required
services:
  - docker
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

env:
  - ORPC_TEST_VERSION="8.0"
  - ORPC_TEST_VERSION="9.0"
  - ORPC_TEST_VERSION="10.0"
  - ORPC_TEST_VERSION="11.0"

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      script: echo "Deploy to PyPi"
      deploy:
        provider: pypi
        user: OCA
        password:
          secure: "OhqjFoTcfHjwYh1VwVtQlSnWug6CikJK2mA1si0hToPqFCtxoVKOmVMUHSqFfkb1W5dVphOC++IT4e7ureIQDxzWQptlItfZMeETQ6y3V2PqTG5x+2jjUofUhYLeYq/W8NaJJDpoZ/CZHxhD9bwUkez2f/B/shBIatHiUfNmIz+bxXIopESIelfBmAojHZioS92NFTQaRC1V8UoNQ2BjZrL1tfjmfSRY1thKVA/SyFjOyhAYPfhFLCOb9FuIgejDbdZI8YLS4DmHOj3IUgm/HvU9uAjejVQlb+5awUSJOPLAL/J9bDWHTs+sWR1AeMEH+t898VKIRq41YhtGnNOEwavVzIRyLkQsma4/lj8aYEO6wqlJQvXR/0Gj7nRbK78NercsXp52s6KuiSsEqRUmj5YqAzwHlG6/0+blNxkv1dLVOb4u0ST0S8KsPGkDgL0jp26+5vl4C6vwpqIJOMfiQXo2Ioh+AWUlT9027hO0ew8ZuQNDxQ9VSR9Czait6umTDDR36zBR2JdYMK0rszA9HT4uNYY9seOqNQKQlTk+aG41go97+CyoV1HyBDuHAmHEau43oCpJhaYpgfYF4v1b3PfmVG2iDSYSkt/nXSdylqXW3aiyzYq8OdVpUz1gG3ypKlIQB6nc5ao+iQTDDKWHv8D2SQx8khlpgA7QCxhf6kk="
        distributions: "sdist bdist_wheel"
        on:
          repo: OCA/odoorpc
          branch: master
          tags: true

before_install:
  - docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4
  - docker run -d -p 8069:8069 --name odoo --link db:db -t "odoo:$ORPC_TEST_VERSION"

install:
  # OdooRPC dependencies
  - pip install sphinx

script:
  - python -m unittest discover -v
  - PYTHONPATH=.:$PYTHONPATH sphinx-build -b doctest -d doc/build/doctrees doc/source build/doctest
